// Package regression contains deterministic regression tests for ferscalc3
// using the TEST_SIMPLE_1.0 scenario format originally developed in the ferex project.
//
// These 9 scenarios (excluding CSRS scenario 08) cover:
//
//	01 - FERS age 62/20yrs:            standard 1.1% multiplier
//	02 - FERS MRA+10 age 57/10yrs:     MRA+10 early retirement reduction
//	03 - FERS age 60/20yrs + fed tax:  federal tax applied
//	04 - FERS SRS age 58/30yrs:        SRS paid until age 62
//	05 - SS claim age 67:              social security starts mid-projection
//	06 - Survivor 10% cost:            50% survivor election reduces pension by 10%
//	07 - State tax 5% + TSP:           TSP fixed withdrawal, multi-level taxes
//	09 - TSP fixed $12k/yr:            TSP-only notable income source
//	10 - Tax-free state + SRS stop:    SRS stops at 62, SS starts
//
// The expected CSVs are generated FROM ferscalc3 (not from ferex), making this a
// ferscalc3 stability test suite. Run with -update flag to regenerate expected CSVs:
//
//	go test ./test/regression/... -run TestUpdateExpectedCSVs -update
//
// Column definitions match ferex's TEST_SIMPLE_1.0 format:
//   - FERSAnnuity: pension + survivor pension (retiree's reduced pension amount)
//   - SRS: FERS Supplement
//   - SocialSecurity: SS benefit for PersonA
//   - TSPWithdrawal: TSP withdrawal for PersonA
//   - TaxFederal: federal income tax
//   - TaxState: state income tax
//   - NetAfterTax: FERSAnnuity + SRS + SS + TSP - TaxFederal - TaxState
//     (excludes FEHB and Medicare premiums, consistent with ferex's formula)
package regression_test

import (
	"encoding/csv"
	"flag"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/rpgo/retirement-calculator/internal/calculation"
	"github.com/rpgo/retirement-calculator/internal/domain"
	"github.com/shopspring/decimal"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"gopkg.in/yaml.v3"
)

// updateExpected is set by -update flag to regenerate expected CSVs.
var updateExpected = flag.Bool("update", false, "regenerate expected CSV files from current ferscalc3 output")

// ─────────────────────────────────────────────────────────────────────────────
// TEST_SIMPLE_1.0 Schema
// ─────────────────────────────────────────────────────────────────────────────

// testScenario represents the TEST_SIMPLE_1.0 YAML input format.
type testScenario struct {
	Ruleset struct {
		Year   int    `yaml:"year"`
		Source string `yaml:"source"`
	} `yaml:"ruleset"`
	Person struct {
		BirthDate      string  `yaml:"birth_date"`
		RetirementDate string  `yaml:"retirement_date"`
		High3          float64 `yaml:"high3"`
		ServiceYears   float64 `yaml:"service_years"`
		FERS           bool    `yaml:"fers"`
		MRA10          bool    `yaml:"mra10"` // if true, uses MRA+10 (under-20-yr) retirement
		SurvivorPct    float64 `yaml:"survivor_pct"`
	} `yaml:"person"`
	TSP struct {
		WithdrawalFixed float64 `yaml:"withdrawal_fixed"` // annual fixed withdrawal
	} `yaml:"tsp"`
	Taxes struct {
		FlatFederalRate float64 `yaml:"flat_federal_rate"`
		FlatStateRate   float64 `yaml:"flat_state_rate"`
	} `yaml:"taxes"`
	Social struct {
		ClaimAge        int     `yaml:"claim_age"`
		Primary         float64 `yaml:"primary"`           // annual SS benefit at FRA
		SSAge62Estimate float64 `yaml:"ss_age62_estimate"` // annual SS benefit at 62
	} `yaml:"social"`
	Simulation struct {
		Years int `yaml:"years"`
		Runs  int `yaml:"runs"`
	} `yaml:"simulation"`
}

// expectedRow holds one year's expected output from the CSV.
// NetAfterTax = FERSAnnuity + SRS + SocialSec + TSPWithdraw - TaxFederal - TaxState
// (excludes FEHB and Medicare to remain consistent with ferex's TEST_SIMPLE_1.0 formula).
type expectedRow struct {
	Year        int
	FERSAnnuity float64
	SRS         float64
	SocialSec   float64
	TSPWithdraw float64
	TaxFederal  float64
	TaxState    float64
	NetAfterTax float64
}

// ─────────────────────────────────────────────────────────────────────────────
// Test Entry Points
// ─────────────────────────────────────────────────────────────────────────────

// TestRegressionSuite validates that ferscalc3's outputs match the expected CSVs.
// The expected CSVs are generated by ferscalc3 itself (see TestUpdateExpectedCSVs).
func TestRegressionSuite(t *testing.T) {
	scenarios, err := filepath.Glob("scenarios/*.yaml")
	require.NoError(t, err)
	require.NotEmpty(t, scenarios, "no scenario YAML files found in scenarios/")

	for _, scenarioFile := range scenarios {
		scenarioFile := scenarioFile
		name := strings.TrimSuffix(filepath.Base(scenarioFile), ".yaml")
		t.Run(name, func(t *testing.T) {
			runRegressionScenario(t, scenarioFile)
		})
	}
}

// TestUpdateExpectedCSVs regenerates the expected CSV files from ferscalc3's current output.
// Run this when the calculation engine is intentionally changed:
//
//	go test ./test/regression/... -run TestUpdateExpectedCSVs -update
func TestUpdateExpectedCSVs(t *testing.T) {
	if !*updateExpected {
		t.Skip("run with -update to regenerate expected CSV files")
	}

	scenarios, err := filepath.Glob("scenarios/*.yaml")
	require.NoError(t, err)
	require.NotEmpty(t, scenarios)

	require.NoError(t, os.MkdirAll("expected", 0o755))

	for _, scenarioFile := range scenarios {
		name := strings.TrimSuffix(filepath.Base(scenarioFile), ".yaml")
		t.Run(name, func(t *testing.T) {
			generateExpectedCSV(t, scenarioFile)
		})
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// Core Runner
// ─────────────────────────────────────────────────────────────────────────────

func runRegressionScenario(t *testing.T, scenarioFile string) {
	t.Helper()

	sc, projection, projectionStartYear := runProjection(t, scenarioFile)

	// Load expected CSV
	baseName := strings.TrimSuffix(filepath.Base(scenarioFile), ".yaml")
	expectedFile := filepath.Join("expected", baseName+".csv")
	expected, err := loadExpectedCSV(t, expectedFile)
	require.NoError(t, err, "reading expected CSV %s", expectedFile)
	require.NotEmpty(t, expected, "expected CSV must have at least one data row")

	// Verify that all expected CSV years fall within the projection bounds.
	for _, row := range expected {
		idx := row.Year - projectionStartYear
		require.GreaterOrEqual(t, idx, 0,
			"CSV year %d is before projectionStartYear %d", row.Year, projectionStartYear)
		require.Less(t, idx, len(projection),
			"CSV year %d maps to projection index %d which is out of bounds (len=%d)",
			row.Year, idx, len(projection))
	}

	// Tolerance: all columns use ±$1 (covering floating-point rounding).
	// Tax columns get ±$2 because ferscalc3 uses bracket-based progressive tax
	// while the original ferex scenarios used flat rates — the expected CSVs
	// are now ferscalc3-native, so the tolerance only covers rounding noise.
	_ = sc // sc used in generateExpectedCSV; suppress "declared but not used"

	for _, row := range expected {
		proj := projection[row.Year-projectionStartYear]
		t.Run(fmt.Sprintf("year_%d", row.Year), func(t *testing.T) {
			// FERS Annuity (pension + any survivor pension, but NOT SRS, NOT SS)
			totalPension := proj.PensionPersonA.Add(proj.SurvivorPensionPersonA).InexactFloat64()
			assert.InDelta(t, row.FERSAnnuity, totalPension, 1.0,
				"FERSAnnuity mismatch in year %d", row.Year)

			// FERS Supplement (SRS)
			assert.InDelta(t, row.SRS, proj.FERSSupplementPersonA.InexactFloat64(), 1.0,
				"SRS mismatch in year %d", row.Year)

			// Social Security
			assert.InDelta(t, row.SocialSec, proj.SSBenefitPersonA.InexactFloat64(), 1.0,
				"SocialSecurity mismatch in year %d", row.Year)

			// TSP Withdrawal
			assert.InDelta(t, row.TSPWithdraw, proj.TSPWithdrawalPersonA.InexactFloat64(), 1.0,
				"TSPWithdrawal mismatch in year %d", row.Year)

			// Federal Tax
			assert.InDelta(t, row.TaxFederal, proj.FederalTax.InexactFloat64(), 1.0,
				"TaxFederal mismatch in year %d", row.Year)

			// State Tax
			assert.InDelta(t, row.TaxState, proj.StateTax.InexactFloat64(), 1.0,
				"TaxState mismatch in year %d", row.Year)

			// Net After Tax: gross - fed tax - state tax (excludes FEHB/Medicare)
			// This matches ferex's NetAfterTax formula:
			//   NetAfterTax = pension + SRS + SS + TSP - fedTax - stateTax
			gross := proj.PensionPersonA.Add(proj.SurvivorPensionPersonA).
				Add(proj.FERSSupplementPersonA).
				Add(proj.SSBenefitPersonA).
				Add(proj.TSPWithdrawalPersonA)
			net := gross.Sub(proj.FederalTax).Sub(proj.StateTax).InexactFloat64()
			assert.InDelta(t, row.NetAfterTax, net, 1.0,
				"NetAfterTax mismatch in year %d", row.Year)
		})
	}
}

// generateExpectedCSV runs ferscalc3 for a scenario and writes the output to
// the expected/ directory. Called by TestUpdateExpectedCSVs.
func generateExpectedCSV(t *testing.T, scenarioFile string) {
	t.Helper()

	_, projection, projectionStartYear := runProjection(t, scenarioFile)

	baseName := strings.TrimSuffix(filepath.Base(scenarioFile), ".yaml")
	outFile := filepath.Join("expected", baseName+".csv")

	f, err := os.Create(outFile)
	require.NoError(t, err, "creating output CSV %s", outFile)
	defer f.Close()

	w := csv.NewWriter(f)
	defer w.Flush()

	require.NoError(t, w.Write([]string{
		"Year", "FERSAnnuity", "SRS", "SocialSecurity",
		"TSPWithdrawal", "TaxFederal", "TaxState", "NetAfterTax",
	}))

	// Write one row per projection year, starting from the retirement year.
	// Skip the pre-retirement year at index 0 (projectionStartYear).
	for i, proj := range projection {
		calYear := projectionStartYear + i
		if i == 0 {
			// Skip the pre-retirement offset year
			continue
		}
		pension := proj.PensionPersonA.Add(proj.SurvivorPensionPersonA)
		srs := proj.FERSSupplementPersonA
		ss := proj.SSBenefitPersonA
		tsp := proj.TSPWithdrawalPersonA
		fedTax := proj.FederalTax
		stateTax := proj.StateTax
		gross := pension.Add(srs).Add(ss).Add(tsp)
		net := gross.Sub(fedTax).Sub(stateTax)

		require.NoError(t, w.Write([]string{
			strconv.Itoa(calYear),
			roundCents(pension),
			roundCents(srs),
			roundCents(ss),
			roundCents(tsp),
			roundCents(fedTax),
			roundCents(stateTax),
			roundCents(net),
		}))
	}

	t.Logf("wrote %s", outFile)
}

// roundCents formats a Decimal as a string rounded to 2 decimal places.
func roundCents(d decimal.Decimal) string {
	f := d.InexactFloat64()
	rounded := math.Round(f*100) / 100
	return strconv.FormatFloat(rounded, 'f', 2, 64)
}

// ─────────────────────────────────────────────────────────────────────────────
// Shared Projection Runner
// ─────────────────────────────────────────────────────────────────────────────

// runProjection loads a scenario YAML, builds ferscalc3 domain objects, runs the
// projection engine, and returns the parsed scenario, the projection slice, and
// projectionStartYear so callers can map CSV year → slice index.
func runProjection(t *testing.T, scenarioFile string) (testScenario, []domain.AnnualCashFlow, int) {
	t.Helper()

	raw, err := os.ReadFile(scenarioFile)
	require.NoError(t, err, "reading scenario file %s", scenarioFile)

	var sc testScenario
	require.NoError(t, yaml.Unmarshal(raw, &sc), "parsing scenario YAML %s", scenarioFile)

	retDate := parseDate(t, sc.Person.RetirementDate)
	personA := buildEmployee(t, sc, retDate)
	personB := buildDummyEmployee()

	scenario := buildScenario(t, sc, personA, retDate)
	assumptions := buildAssumptions(t, sc)

	engine := calculation.NewCalculationEngineWithConfig(assumptions)
	projection := engine.GenerateAnnualProjection(personA, personB, scenario, &assumptions, assumptions.FederalRules)

	// projectionStartYear is one year before the retirement year.
	// projection[0] corresponds to projectionStartYear (pre-retirement).
	// projection[1] corresponds to the retirement year.
	retYear := retDate.Year()
	projectionStartYear := retYear - 1
	if projectionStartYear < sc.Ruleset.Year {
		projectionStartYear = sc.Ruleset.Year
	}

	return sc, projection, projectionStartYear
}

// ─────────────────────────────────────────────────────────────────────────────
// Domain Object Builders
// ─────────────────────────────────────────────────────────────────────────────

func buildEmployee(t *testing.T, sc testScenario, retDate time.Time) *domain.Employee {
	t.Helper()

	birthDate := parseDate(t, sc.Person.BirthDate)

	// Derive hire date: retirement_date minus service_years (integer years, approximate).
	// For MRA+10 scenarios the service is exactly stated; we trust the YAML value.
	hireDate := retDate.AddDate(-int(sc.Person.ServiceYears), 0, 0)

	// SS benefits in scenario are annual; ferscalc3 stores monthly
	ssAt62Monthly := decimal.NewFromFloat(sc.Social.SSAge62Estimate / 12.0)
	ssAtFRAMonthly := decimal.NewFromFloat(sc.Social.Primary / 12.0)

	return &domain.Employee{
		Name:                           "PersonA",
		BirthDate:                      birthDate,
		HireDate:                       hireDate,
		EmploymentType:                 domain.EmploymentTypeFederal,
		High3Salary:                    decimal.NewFromFloat(sc.Person.High3),
		SSBenefit62:                    ssAt62Monthly,
		SSBenefitFRA:                   ssAtFRAMonthly,
		SurvivorBenefitElectionPercent: decimal.NewFromFloat(sc.Person.SurvivorPct),
		// TSP: set an initial balance only if the scenario uses TSP withdrawals;
		// use a large enough balance so it doesn't deplete during the projection.
		TSPBalanceTraditional: tspBalanceForScenario(sc),
		TSPBalanceRoth:        decimal.Zero,
	}
}

// buildDummyEmployee creates a non-federal placeholder for PersonB.
// ferscalc3 requires two persons; PersonB contributes nothing to the calculation.
func buildDummyEmployee() *domain.Employee {
	return &domain.Employee{
		Name:           "PersonB",
		BirthDate:      time.Date(1970, 1, 1, 0, 0, 0, 0, time.UTC),
		HireDate:       time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC),
		EmploymentType: domain.EmploymentTypeNonFederal,
	}
}

func buildScenario(t *testing.T, sc testScenario, personA *domain.Employee, retDate time.Time) *domain.Scenario {
	t.Helper()

	strategy := "none"
	var targetMonthly *decimal.Decimal
	if sc.TSP.WithdrawalFixed > 0 {
		strategy = "need_based"
		v := decimal.NewFromFloat(sc.TSP.WithdrawalFixed / 12.0)
		targetMonthly = &v
	}

	// PersonB retires at same date but has no income; set far-future retirement
	// so she is never "retired" in the projection (non-federal, no pension).
	personBRetDate := retDate.AddDate(40, 0, 0)

	return &domain.Scenario{
		Name: "regression",
		PersonA: domain.RetirementScenario{
			EmployeeName:               "PersonA",
			RetirementDate:             retDate,
			SSStartAge:                 sc.Social.ClaimAge,
			TSPWithdrawalStrategy:      strategy,
			TSPWithdrawalTargetMonthly: targetMonthly,
		},
		PersonB: domain.RetirementScenario{
			EmployeeName:          "PersonB",
			RetirementDate:        personBRetDate,
			SSStartAge:            70,
			TSPWithdrawalStrategy: "none",
		},
	}
}

func buildAssumptions(t *testing.T, sc testScenario) domain.GlobalAssumptions {
	t.Helper()

	// TEST_SIMPLE_1.0 uses zero COLA, zero inflation, zero TSP growth.
	// This makes projections fully deterministic.
	baseYear := sc.Ruleset.Year
	if baseYear == 0 {
		baseYear = 2025
	}
	// projectionBaseYear is one year before retirement so that projection[1]
	// corresponds to the first full year of retirement (matching the CSV rows).
	retYear, _ := strconv.Atoi(sc.Person.RetirementDate[:4])
	projBaseYear := retYear - 1
	if projBaseYear < baseYear {
		projBaseYear = baseYear
	}

	return domain.GlobalAssumptions{
		InflationRate:               decimal.Zero, // deterministic: no inflation
		FEHBPremiumInflation:        decimal.Zero,
		TSPReturnPreRetirement:      decimal.Zero,
		TSPReturnPostRetirement:     decimal.Zero,
		COLAGeneralRate:             decimal.Zero, // no COLA in TEST_SIMPLE_1.0
		FederalBracketInflationRate: decimal.Zero,
		// projBaseYear is one year before retirement; add 1 so the projection
		// covers the full CSV range (projBaseYear, retirementYear, ..., retirementYear+years-1).
		ProjectionYears:    sc.Simulation.Years + 1,
		ProjectionBaseYear: projBaseYear,
		CurrentLocation: domain.Location{
			State: "Pennsylvania",
		},
		FederalRules: defaultFederalRules(),
	}
}

func defaultFederalRules() domain.FederalRules {
	return domain.FederalRules{
		FERSRules: domain.FERSRules{
			SRSEarningsLimit: decimal.NewFromInt(23400),
		},
		FederalTaxConfig: domain.FederalTaxConfig{
			StandardDeductionMFJ:        decimal.NewFromInt(30000),
			StandardDeductionSingle:     decimal.NewFromInt(15000),
			AdditionalStandardDeduction: decimal.NewFromInt(1600),
		},
		StateLocalTaxConfig: domain.StateLocalTaxConfig{
			PennsylvaniaRate: decimal.NewFromFloat(0.0307),
		},
		MedicareConfig: domain.MedicareConfig{
			// BasePremium2025 = 0 signals "no Medicare" in the regression harness.
			// Note: NewMedicareCalculatorWithConfig treats zero as "use default",
			// so the harness excludes Medicare from NetAfterTax by using the
			// explicit gross - tax formula rather than proj.NetIncome.
			BasePremium2025:      decimal.Zero,
			PremiumInflationRate: decimal.Zero,
		},
	}
}

// tspBalanceForScenario sets a large enough TSP balance if the scenario has TSP withdrawals.
func tspBalanceForScenario(sc testScenario) decimal.Decimal {
	if sc.TSP.WithdrawalFixed <= 0 {
		return decimal.Zero
	}
	// Provide 50× the annual withdrawal as initial balance to prevent depletion
	return decimal.NewFromFloat(sc.TSP.WithdrawalFixed * 50)
}

// ─────────────────────────────────────────────────────────────────────────────
// CSV Helpers
// ─────────────────────────────────────────────────────────────────────────────

func loadExpectedCSV(t *testing.T, path string) ([]expectedRow, error) {
	t.Helper()
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	r := csv.NewReader(f)
	records, err := r.ReadAll()
	if err != nil {
		return nil, err
	}

	// Skip header row
	var rows []expectedRow
	for _, rec := range records[1:] {
		if len(rec) < 8 {
			continue
		}
		row := expectedRow{
			Year:        parseInt(t, rec[0]),
			FERSAnnuity: parseFloat(t, rec[1]),
			SRS:         parseFloat(t, rec[2]),
			SocialSec:   parseFloat(t, rec[3]),
			TSPWithdraw: parseFloat(t, rec[4]),
			TaxFederal:  parseFloat(t, rec[5]),
			TaxState:    parseFloat(t, rec[6]),
			NetAfterTax: parseFloat(t, rec[7]),
		}
		rows = append(rows, row)
	}
	return rows, nil
}

func parseInt(t *testing.T, s string) int {
	t.Helper()
	v, err := strconv.Atoi(strings.TrimSpace(s))
	require.NoError(t, err, "parseInt(%q)", s)
	return v
}

func parseFloat(t *testing.T, s string) float64 {
	t.Helper()
	v, err := strconv.ParseFloat(strings.TrimSpace(s), 64)
	require.NoError(t, err, "parseFloat(%q)", s)
	return v
}

func parseDate(t *testing.T, s string) time.Time {
	t.Helper()
	d, err := time.Parse("2006-01-02", s)
	require.NoError(t, err, "parseDate(%q)", s)
	return d
}
